=== enzo1982/BoCA/doc/dtds/component.dtd
<!-- BoCA component XML description DTD -->

<!ENTITY % BoCA.Version "-//DTD BoCA 1.0 Draft//EN">

<!ELEMENT component (name, version, id, type, require*, replace*, conflict*, precede*, succeed*, format*, input*, tagspec*, external*, parameters?)>

	<!ELEMENT name (#PCDATA)>

	<!ELEMENT version (#PCDATA)>
	<!ATTLIST version debug (true|false) "false">

	<!ELEMENT id (#PCDATA)>

	<!ELEMENT type (#PCDATA)>
	<!ATTLIST type threadSafe (true|false) "true">

	<!ELEMENT require (#PCDATA)>
	<!ELEMENT replace (#PCDATA)>
	<!ELEMENT conflict (#PCDATA)>
	<!ELEMENT precede (#PCDATA)>
	<!ELEMENT succeed (#PCDATA)>

	<!ELEMENT format (name, lossless?, extension+, companion*, tag*)>

		<!ELEMENT lossless (#PCDATA)>
		<!ELEMENT extension (#PCDATA)>
		<!ELEMENT companion (#PCDATA)>

		<!ELEMENT tag (#PCDATA)>
		<!ATTLIST tag id   NMTOKEN		  #REQUIRED
			      mode (prepend|append|other) #REQUIRED>

	<!ELEMENT input EMPTY>
	<!ATTLIST input float	 (true|false) "false"
			signed	 (true|false) "true"
			bits	 CDATA #IMPLIED
			channels CDATA #IMPLIED
			rate	 CDATA #IMPLIED>

	<!ELEMENT tagspec (name, coverart?, encodings?)>
	<!ATTLIST tagspec default (true|false) "true">

		<!ELEMENT coverart (#PCDATA)>
		<!ATTLIST coverart supported (true|false) "false"
				   default   (true|false) "true">

		<!ELEMENT prependzero (#PCDATA)>
		<!ATTLIST prependzero allowed (true|false) "false"
				      default (true|false) "false">

		<!ELEMENT encodings (encoding*)>
		<!ATTLIST encodings free (true|false) "false">

			<!ELEMENT encoding (#PCDATA)>
			<!ATTLIST encoding default (true|false) #IMPLIED>

	<!ELEMENT external (command, arguments, mode, (informat?, outformat?), parameters?)>

		<!ELEMENT command (#PCDATA)>
		<!ATTLIST command ignoreExitCode (true|false) "false">

		<!ELEMENT arguments (#PCDATA)>
		<!ELEMENT mode (#PCDATA)>
		<!ELEMENT informat (#PCDATA)>
		<!ELEMENT outformat (#PCDATA)>

		<!ELEMENT parameters (switch | selection | range)*>

			<!ELEMENT switch (requires*, depends*)>
			<!ATTLIST switch name	  CDATA	#REQUIRED
					 argument CDATA	#REQUIRED
					 enabled  (true|false) "false"
					 hidden	  (true|false) "false">

			<!ELEMENT selection (requires*, depends*, option+)>
			<!ATTLIST selection name     CDATA   #REQUIRED
					    argument CDATA   #REQUIRED
					    enabled  (true|false) "false"
					    default  NMTOKEN #IMPLIED
					    hidden   (true|false) "false">

				<!ELEMENT option (#PCDATA)>
				<!ATTLIST option alias CDATA #IMPLIED>

			<!ELEMENT range (requires*, depends*, min, max)>
			<!ATTLIST range name	 CDATA	 #REQUIRED
					argument CDATA	 #REQUIRED
					enabled	 (true|false) "false"
					default	 NMTOKEN #IMPLIED
					step	 NMTOKEN #IMPLIED
					hidden	 (true|false) "false">

				<!ELEMENT min (#PCDATA)>
				<!ATTLIST min alias CDATA #IMPLIED>

				<!ELEMENT max (#PCDATA)>
				<!ATTLIST max alias CDATA #IMPLIED>

			<!ELEMENT requires (#PCDATA)>
			<!ATTLIST requires option CDATA #IMPLIED
					   args   CDATA #IMPLIED
					   stream (stdout|stderr) "stdout">

			<!ELEMENT depends (#PCDATA)>
			<!ATTLIST depends setting CDATA	#REQUIRED
					  state	  (enabled|disabled) "enabled"
					  value	  CDATA #IMPLIED>

		<!ELEMENT md5 (#PCDATA)>
		<!ATTLIST md5 stream  (stdout|stderr) "stdout"
			      require CDATA #IMPLIED
			      prefix  CDATA #IMPLIED>

=== enzo1982/BoCA/scripts/boca_decoder_avconv_webm_audio.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>WebM Audio Extractor</name>
  <version>1.0</version>
  <id>avconv-webm_audio-in</id>
  <type>decoder</type>
  <format>
    <name>WebM Video</name>
    <extension>webm</extension>
  </format>
  <external>
    <command>avconv</command>
    <arguments>-i %INFILE -vn %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
</component>

=== enzo1982/BoCA/scripts/unix/boca_decoder_wavpack.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>WavPack Audio Decoder</name>
  <version>1.0</version>
  <id>wv-dec</id>
  <type>decoder</type>
  <replace>ffmpeg-wv-dec</replace>
  <format>
    <name>WavPack Files</name>
    <extension>wv</extension>
    <companion>wvc</companion>
    <tag id="apev2-tag" mode="append">APEv2</tag>
  </format>
  <external>
    <command ignoreExitCode="true">wvunpack</command>
    <arguments>%OPTIONS %INFILE -o -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
    <md5 require="lossless" prefix="original md5:">-s %INFILE</md5>
    <parameters>
      <range name="Number of threads to use" argument="--threads=%VALUE" enabled="true" default="1" hidden="true">
	<requires option="--threads[=n]" arguments="--help"/>
	<min>1</min>
	<max>12</max>
      </range>
    </parameters>
  </external>
</component>

=== enzo1982/BoCA/scripts/boca_encoder_aften.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Aften A/52 (AC-3) Encoder</name>
  <version>1.0</version>
  <id>aften-enc</id>
  <type>encoder</type>
  <replace>avconv-ac3-enc</replace>
  <format>
    <name>AC-3 Files</name>
    <extension>ac3</extension>
    <channels>6</channels>
  </format>
  <external>
    <command>aften</command>
    <arguments>%OPTIONS %INFILE %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
  </external>
</component>

=== enzo1982/BoCA/scripts/win32/boca_encoder_wavpack.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>WavPack Audio Encoder</name>
  <version>1.0</version>
  <id>wv-enc</id>
  <type>encoder</type>
  <format>
    <name>WavPack Files</name>
    <extension>wv</extension>
    <companion>wvc</companion>
    <tag id="apev2-tag" mode="append">APEv2</tag>
  </format>
  <external>
    <command>wavpack</command>
    <arguments>-i -m %OPTIONS - %OUTFILE</arguments>
    <mode>stdio</mode>
    <informat>wave</informat>
    <parameters>
      <range name="Number of threads to use" argument="--threads=%VALUE" enabled="true" default="%THREADS" hidden="true">
	<requires option="--threads[=n]" arguments="--help"/>
	<min>1</min>
	<max>12</max>
      </range>
      <range name="Enable lossy compression" argument="-b%VALUE" default="256" step="8">
	<min alias="%1 kbps">64</min>
	<max alias="%1 kbps">720</max>
      </range>
      <switch name="Create correction file" argument="-c">
	<depends setting="Enable lossy compression"/>
      </switch>
      <selection name="Compression mode" argument="%VALUE" default="-h">
	<option alias="fast">-f</option>
	<option alias="high quality">-h</option>
	<option alias="very high quality">-hh</option>
      </selection>
      <range name="Extra encode processing" argument="-x%VALUE" default="1">
	<min alias="faster">1</min>
	<max alias="better">6</max>
      </range>
    </parameters>
  </external>
</component>

=== enzo1982/BoCA/scripts/boca_decoder_avconv_ac3.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>AC3 Audio Decoder</name>
  <version>1.0</version>
  <id>avconv-ac3-dec</id>
  <type>decoder</type>
  <format>
    <name>AC3 Files</name>
    <extension>ac3</extension>
  </format>
  <external>
    <command>avconv</command>
    <arguments>-i %INFILE %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
    <parameters>
      <switch name="Downmix multi-channel audio to stereo" argument="-ac 2"/>
    </parameters>
  </external>
  <external>
    <command>ffmpeg</command>
    <arguments>-i %INFILE %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
    <parameters>
      <switch name="Downmix multi-channel audio to stereo" argument="-ac 2"/>
    </parameters>
  </external>
</component>

=== enzo1982/BoCA/scripts/boca_decoder_ffmpeg_tak.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Tom's Audiokompressor</name>
  <version>1.0</version>
  <id>ffmpeg-tak-dec</id>
  <type>decoder</type>
  <format>
    <name>Tom's Audio</name>
    <lossless>true</lossless>
    <extension>tak</extension>
    <tag id="apev2-tag" mode="append">APEv2</tag>
  </format>
  <external>
    <command>ffmpeg</command>
    <arguments>-i %INFILE %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
    <md5 stream="stderr" prefix="MD5=">-v 40 -i %INFILE</md5>
  </external>
  <external>
    <command>avconv</command>
    <arguments>-i %INFILE %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
    <md5 stream="stderr" prefix="MD5=">-v 40 -i %INFILE</md5>
  </external>
</component>

=== enzo1982/BoCA/scripts/boca_encoder_avconv_wma.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Windows Media Audio Encoder</name>
  <version>1.0</version>
  <id>avconv-wma-enc</id>
  <type>encoder</type>
  <format>
    <name>Windows Media Audio Files</name>
    <extension>wma</extension>
    <tag id="wma-tag" mode="other">WMA Metadata</tag>
  </format>
  <external>
    <command>avconv</command>
    <arguments>-f wav -i %INFILE -c:a wmav2 %OPTIONS -y %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
    <parameters>
      <range name="Bitrate" argument="-b:a %VALUE000" default="192" enabled="true" step="4">
	<min alias="%1 kbps">24</min>
	<max alias="%1 kbps">320</max>
      </range>
    </parameters>
  </external>
  <external>
    <command>ffmpeg</command>
    <arguments>-f wav -i %INFILE -acodec wmav2 %OPTIONS -y %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
    <parameters>
      <range name="Bitrate" argument="-b:a %VALUE000" default="192" enabled="true" step="4">
	<min alias="%1 kbps">24</min>
	<max alias="%1 kbps">320</max>
      </range>
    </parameters>
  </external>
</component>

=== enzo1982/BoCA/scripts/boca_decoder_avconv_mpg_audio.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>MPEG Video Audio Extractor</name>
  <version>1.0</version>
  <id>avconv-mpg_audio-in</id>
  <type>decoder</type>
  <format>
    <name>MPEG Video Files</name>
    <extension>mpg</extension>
    <extension>mpeg</extension>
  </format>
  <external>
    <command>avconv</command>
    <arguments>-i %INFILE -vn %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
  <external>
    <command>ffmpeg</command>
    <arguments>-i %INFILE -vn %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
</component>
