=== enzo1982/BoCA/doc/dtds/component.dtd
<!-- BoCA component XML description DTD -->

<!ENTITY % BoCA.Version "-//DTD BoCA 1.0 Draft//EN">

<!ELEMENT component (name, version, id, type, require*, replace*, conflict*, precede*, succeed*, format*, input*, tagspec*, external*, parameters?)>

	<!ELEMENT name (#PCDATA)>

	<!ELEMENT version (#PCDATA)>
	<!ATTLIST version debug (true|false) "false">

	<!ELEMENT id (#PCDATA)>

	<!ELEMENT type (#PCDATA)>
	<!ATTLIST type threadSafe (true|false) "true">

	<!ELEMENT require (#PCDATA)>
	<!ELEMENT replace (#PCDATA)>
	<!ELEMENT conflict (#PCDATA)>
	<!ELEMENT precede (#PCDATA)>
	<!ELEMENT succeed (#PCDATA)>

	<!ELEMENT format (name, lossless?, extension+, companion*, tag*)>

		<!ELEMENT lossless (#PCDATA)>
		<!ELEMENT extension (#PCDATA)>
		<!ELEMENT companion (#PCDATA)>

		<!ELEMENT tag (#PCDATA)>
		<!ATTLIST tag id   NMTOKEN		  #REQUIRED
			      mode (prepend|append|other) #REQUIRED>

	<!ELEMENT input EMPTY>
	<!ATTLIST input float	 (true|false) "false"
			signed	 (true|false) "true"
			bits	 CDATA #IMPLIED
			channels CDATA #IMPLIED
			rate	 CDATA #IMPLIED>

	<!ELEMENT tagspec (name, coverart?, encodings?)>
	<!ATTLIST tagspec default (true|false) "true">

		<!ELEMENT coverart (#PCDATA)>
		<!ATTLIST coverart supported (true|false) "false"
				   default   (true|false) "true">

		<!ELEMENT prependzero (#PCDATA)>
		<!ATTLIST prependzero allowed (true|false) "false"
				      default (true|false) "false">

		<!ELEMENT encodings (encoding*)>
		<!ATTLIST encodings free (true|false) "false">

			<!ELEMENT encoding (#PCDATA)>
			<!ATTLIST encoding default (true|false) #IMPLIED>

	<!ELEMENT external (command, arguments, mode, (informat?, outformat?), parameters?)>

		<!ELEMENT command (#PCDATA)>
		<!ATTLIST command ignoreExitCode (true|false) "false">

		<!ELEMENT arguments (#PCDATA)>
		<!ELEMENT mode (#PCDATA)>
		<!ELEMENT informat (#PCDATA)>
		<!ELEMENT outformat (#PCDATA)>

		<!ELEMENT parameters (switch | selection | range)*>

			<!ELEMENT switch (requires*, depends*)>
			<!ATTLIST switch name	  CDATA	#REQUIRED
					 argument CDATA	#REQUIRED
					 enabled  (true|false) "false"
					 hidden	  (true|false) "false">

			<!ELEMENT selection (requires*, depends*, option+)>
			<!ATTLIST selection name     CDATA   #REQUIRED
					    argument CDATA   #REQUIRED
					    enabled  (true|false) "false"
					    default  NMTOKEN #IMPLIED
					    hidden   (true|false) "false">

				<!ELEMENT option (#PCDATA)>
				<!ATTLIST option alias CDATA #IMPLIED>

			<!ELEMENT range (requires*, depends*, min, max)>
			<!ATTLIST range name	 CDATA	 #REQUIRED
					argument CDATA	 #REQUIRED
					enabled	 (true|false) "false"
					default	 NMTOKEN #IMPLIED
					step	 NMTOKEN #IMPLIED
					hidden	 (true|false) "false">

				<!ELEMENT min (#PCDATA)>
				<!ATTLIST min alias CDATA #IMPLIED>

				<!ELEMENT max (#PCDATA)>
				<!ATTLIST max alias CDATA #IMPLIED>

			<!ELEMENT requires (#PCDATA)>
			<!ATTLIST requires option CDATA #IMPLIED
					   args   CDATA #IMPLIED
					   stream (stdout|stderr) "stdout">

			<!ELEMENT depends (#PCDATA)>
			<!ATTLIST depends setting CDATA	#REQUIRED
					  state	  (enabled|disabled) "enabled"
					  value	  CDATA #IMPLIED>

		<!ELEMENT md5 (#PCDATA)>
		<!ATTLIST md5 stream  (stdout|stderr) "stdout"
			      require CDATA #IMPLIED
			      prefix  CDATA #IMPLIED>

=== enzo1982/BoCA/scripts/boca_decoder_avconv_m4v_audio.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>MP4 Video Audio Extractor</name>
  <version>1.0</version>
  <id>avconv-m4v_audio-in</id>
  <type>decoder</type>
  <format>
    <name>MP4 Video Files</name>
    <extension>m4v</extension>
    <tag id="mp4-tag" mode="other">MP4 Metadata</tag>
  </format>
  <external>
    <command>avconv</command>
    <arguments>-i %INFILE -vn %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
  <external>
    <command>ffmpeg</command>
    <arguments>-i %INFILE -vn %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
</component>

=== enzo1982/BoCA/scripts/win32/boca_encoder_qaac.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>QuickTime AAC Encoder</name>
  <version>1.0</version>
  <id>qaac-enc</id>
  <type>encoder</type>
  <format>
    <name>MP4 Audio Files</name>
    <extension>m4a</extension>
    <tag id="mp4-tag" mode="other">MP4 Metadata</tag>
  </format>
  <external>
    <command>qaac</command>
    <arguments>--ignorelength %OPTIONS -o %OUTFILE -</arguments>
    <mode>stdio</mode>
    <informat>wave</informat>
    <parameters>
      <range name="True VBR Mode" argument="--tvbr %VALUE" default="60" step="1" enabled="true">
	<min alias="worse">0</min>
	<max alias="better">127</max>
      </range>
      <range name="Constrained VBR Mode" argument="--cvbr %VALUE" default="128" step="8">
	<min alias="8 kbps">8</min>
	<max alias="320 kbps">320</max>
      </range>
      <range name="ABR Mode" argument="--abr %VALUE" default="128" step="8">
	<min alias="8 kbps">8</min>
	<max alias="320 kbps">320</max>
      </range>
      <range name="CBR Mode" argument="--cbr %VALUE" default="128" step="8">
	<min alias="8 kbps">8</min>
	<max alias="320 kbps">320</max>
      </range>
      <selection name="Quality" argument="--quality %VALUE" default="2" enabled="true">
	<option alias="High">2</option>
	<option alias="Normal">1</option>
	<option alias="Fast">0</option>
      </selection>
      <selection name="Samplerate" argument="--rate %VALUE" default="auto" enabled="true">
	<option alias="Auto">auto</option>
	<option alias="Keep">keep</option>
	<option alias="8.000 Hz">8000</option>
	<option alias="11.025 Hz">11025</option>
	<option alias="12.000 Hz">12000</option>
	<option alias="16.000 Hz">16000</option>
	<option alias="22.050 Hz">22050</option>
	<option alias="24.000 Hz">24000</option>
	<option alias="32.000 Hz">32000</option>
	<option alias="44.100 Hz">44100</option>
	<option alias="48.000 Hz">48000</option>
      </selection>
      <switch name="Enable HE-AAC Mode" argument="--he"/>
    </parameters>
  </external>
  <external>
    <command>qaac64</command>
    <arguments>--ignorelength %OPTIONS -o %OUTFILE -</arguments>
    <mode>stdio</mode>
    <informat>wave</informat>
    <parameters>
      <range name="True VBR Mode" argument="--tvbr %VALUE" default="60" step="1" enabled="true">
	<min alias="worse">0</min>
	<max alias="better">127</max>
      </range>
      <range name="Constrained VBR Mode" argument="--cvbr %VALUE" default="128" step="8">
	<min alias="8 kbps">8</min>
	<max alias="320 kbps">320</max>
      </range>
      <range name="ABR Mode" argument="--abr %VALUE" default="128" step="8">
	<min alias="8 kbps">8</min>
	<max alias="320 kbps">320</max>
      </range>
      <range name="CBR Mode" argument="--cbr %VALUE" default="128" step="8">
	<min alias="8 kbps">8</min>
	<max alias="320 kbps">320</max>
      </range>
      <selection name="Quality" argument="--quality %VALUE" default="2" enabled="true">
	<option alias="High">2</option>
	<option alias="Normal">1</option>
	<option alias="Fast">0</option>
      </selection>
      <selection name="Samplerate" argument="--rate %VALUE" default="auto" enabled="true">
	<option alias="Auto">auto</option>
	<option alias="Keep">keep</option>
	<option alias="8.000 Hz">8000</option>
	<option alias="11.025 Hz">11025</option>
	<option alias="12.000 Hz">12000</option>
	<option alias="16.000 Hz">16000</option>
	<option alias="22.050 Hz">22050</option>
	<option alias="24.000 Hz">24000</option>
	<option alias="32.000 Hz">32000</option>
	<option alias="44.100 Hz">44100</option>
	<option alias="48.000 Hz">48000</option>
      </selection>
      <switch name="Enable HE-AAC Mode" argument="--he"/>
    </parameters>
  </external>
</component>

=== enzo1982/BoCA/scripts/boca_decoder_ffmpeg_wma.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Windows Media Audio Decoder</name>
  <version>1.0</version>
  <id>ffmpeg-wma-in</id>
  <type>decoder</type>
  <format>
    <name>Windows Media Audio Files</name>
    <extension>wma</extension>
    <tag id="wma-tag" mode="other">WMA Metadata</tag>
  </format>
  <external>
    <command>ffmpeg</command>
    <arguments>-i %INFILE %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
</component>

=== enzo1982/BoCA/scripts/boca_decoder_avconv_alac.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Apple Lossless Decoder</name>
  <version>1.0</version>
  <id>avconv-alac-dec</id>
  <type>decoder</type>
  <replace>alac-dec</replace>
  <format>
    <name>Apple Lossless Files</name>
    <extension>m4a</extension>
    <tag id="mp4-tag" mode="other">MP4 Metadata</tag>
  </format>
  <external>
    <command>avconv</command>
    <arguments>-i %INFILE %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
  <external>
    <command>ffmpeg</command>
    <arguments>-i %INFILE %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
</component>

=== enzo1982/BoCA/scripts/win32/boca_encoder_divxaac.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>DivX AAC Encoder</name>
  <version>1.0</version>
  <id>divxaac-enc</id>
  <type>encoder</type>
  <format>
    <name>AAC Audio Files</name>
    <extension>aac</extension>
  </format>
  <external>
    <command>DivXAACEnc</command>
    <arguments>-i %INFILE -o %OUTFILE %OPTIONS</arguments>
    <mode>file</mode>
    <informat>wave</informat>
    <parameters>
      <selection name="HE-AAC Mode" argument="-e %VALUE" default="0" enabled="false">
	<option alias="Disabled">0</option>
	<option alias="HE-AAC v1">1</option>
	<option alias="HE-AAC v2">2</option>
      </selection>
      <selection name="VBR Mode" argument="-v %VALUE" default="8" enabled="true">
	<option alias="Disabled">0</option>
	<option alias="Low quality VBR mode 1">1</option>
	<option alias="Low quality VBR mode 2">2</option>
	<option alias="Low quality VBR mode 3">3</option>
	<option alias="Medium quality VBR mode 1">4</option>
	<option alias="Medium quality VBR mode 2">5</option>
	<option alias="Medium quality VBR mode 3">6</option>
	<option alias="High quality VBR mode 1">7</option>
	<option alias="High quality VBR mode 2">8</option>
	<option alias="High quality VBR mode 3">9</option>
      </selection>
      <selection name="CBR Bitrate" argument="-b %VALUE" default="192" enabled="false">
	<option alias="6 kbps">6</option>
	<option alias="7 kbps">7</option>
	<option alias="8 kbps">8</option>
	<option alias="10 kbps">10</option>
	<option alias="12 kbps">12</option>
	<option alias="14 kbps">14</option>
	<option alias="16 kbps">16</option>
	<option alias="20 kbps">20</option>
	<option alias="24 kbps">24</option>
	<option alias="28 kbps">28</option>
	<option alias="32 kbps">32</option>
	<option alias="40 kbps">40</option>
	<option alias="48 kbps">48</option>
	<option alias="56 kbps">56</option>
	<option alias="64 kbps">64</option>
	<option alias="80 kbps">80</option>
	<option alias="96 kbps">96</option>
	<option alias="112 kbps">112</option>
	<option alias="128 kbps">128</option>
	<option alias="160 kbps">160</option>
	<option alias="192 kbps">192</option>
	<option alias="224 kbps">224</option>
	<option alias="256 kbps">256</option>
	<option alias="320 kbps">320</option>
	<option alias="384 kbps">384</option>
	<option alias="448 kbps">448</option>
	<option alias="512 kbps">512</option>
	<option alias="640 kbps">640</option>
	<option alias="768 kbps">768</option>
	<option alias="896 kbps">896</option>
	<option alias="1024 kbps">1024</option>
      </selection>
      <selection name="Cutoff setting" argument="-f %VALUE" default="1" enabled="false">
	<option alias="Disabled">0</option>
	<option alias="Auto">1</option>
      </selection>
      <range name="Cutoff frequency" argument="-f %VALUE" default="16000" step="250" enabled="false">
	<min alias="1 kHz">1000</min>
	<max alias="24 kHz">24000</max>
      </range>
    </parameters>
  </external>
</component>

=== enzo1982/BoCA/scripts/win32/boca_encoder_tak.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Tom's Audiokompressor</name>
  <version>1.0</version>
  <id>tak-enc</id>
  <type>encoder</type>
  <format>
    <name>Tom's Audio</name>
    <lossless>true</lossless>
    <extension>tak</extension>
    <tag id="apev2-tag" mode="append">APEv2</tag>
  </format>
  <input bits="8" signed="false" channels="1-6"/>
  <input bits="16-24" channels="1-6"/>
  <external>
    <command>takc</command>
    <arguments>-e -ihs %OPTIONS - %OUTFILE</arguments>
    <mode>stdio</mode>
    <informat>wave</informat>
    <parameters>
      <range name="Number of threads to use" argument="-tn%VALUE" enabled="true" default="%THREADS" hidden="true">
	<requires option="-tn#"/>
	<min>1</min>
	<max>4</max>
      </range>
      <range name="Encoder preset" argument="-p%VALUE" default="2">
	<min alias="fastest">0</min>
	<max alias="strongest">4</max>
      </range>
      <selection name="Frame size limit" argument="-fsl%VALUE">
	<option>512</option>
	<option>1024</option>
	<option>2048</option>
	<option>4096</option>
	<option>8192</option>
	<option>16384</option>
      </selection>
      <switch name="Add MD5 checksum" argument="-md5" enabled="true"/>
    </parameters>
  </external>
</component>
